WhoTrades/rds

src/views/site/_releaseRequestRow.php
[*] Column format fix #WTA-2396
=> Column format fix

src/commands/DeployController.php, src/components/Deploy/DeployEventInterface.php, src/components/Deploy/GenericEvent.php, src/config/main.php, src/views/site/_releaseRequestRow.php
[+] Before/after events added for each message handler.
[-] Wtflow module dependency removed
#WTA-2404
=> New events. Unnecessary dependencies removed.

src/commands/DeployController.php
Fix activation notification if previous release request doesn't exist
=> [*] Fix activation notification #WTA-2464

src/assets/TimeJsAsset.php, src/views/site/_releaseRequestRow.php, src/views/site/index.php
[*] Release request create date now rendered at client side with dayjs library
=> Release request create date client side rendering

src/commands/DeployController.php, src/models/ReleaseRequest.php
[*] Release request installed notification now sent only after all builds of parent and child release requests are installed
=> Release request install notification fix

src/commands/DeployController.php
[*] Websocket notification for parent release request when child one is updated
=> Websocket notification for parent release request

src/commands/DeployController.php
Improve activation result processing
=> [*] Improve activation result processing #WTA-2542

src/commands/DeployController.php
[*]Fixed performance issue with disabling old tool jobs when are too many of these jobs
=> Fixed performance issue with disabling old tool jobs

composer.json, src/commands/DeployController.php, src/events/Deploy/CronConfigAfterEvent.php, src/events/Deploy/CronConfigBeforeEvent.php, src/events/Deploy/CronConfigPreCommitEvent.php, src/events/Deploy/UsedVersionAfterEvent.php, src/events/Deploy/UsedVersionBeforeEvent.php, src/events/Deploy/UsedVersionPreCommitEvent.php, src/services/DeployService.php
- GenericEvent replaced with separate event classes
=> Separate classes for each event type

src/views/site/index.php
- Fixed wrong release status error when reinstalling
=> "Wrong release status" error

src/config/main.php
- Removed static require-dev dependency in configuration
=> Removed static yii/debug dependency

composer.json, composer.lock, src/migrations/m201228_141538_add_column_project_script_post_use.php, src/models/Project.php, src/models/ReleaseRequest.php, src/views/project/update-script-deploy.php
- Added post-use script field
- Cron configuration now passed to UseTask
=> Post use script

src/helpers/ReleaseRequest.php
=> Migration display bugfix

src/views/site/_releaseRequestForm.php
=> Stash URI renderer bugfix

composer.json, composer.lock, src/config/main.php, src/extensions/PsrTarget/PsrTarget.php
[+] Added PSR-compatible logging via Monolog
=> Introduced PSR compatible Monolog logging

src/config/main.php
=> SQL info logs filtered out

composer.json, composer.lock
- Static amqplib version due to backward incompatible changes
=> Static amqplib version due to backward incompatible changes

src/commands/DeployController.php, src/models/ReleaseRequest.php, src/services/DeployService.php
- Fixed bug in Release Request rollback when child Release Request fails
=> [CRITICAL] Release request rollback bugfix

src/commands/DeployController.php
- Use messages processing order fix
=> Use messages processing order fix

src/events/NotificationEventHandler.php, src/services/NotificationService.php
- PSR compatible exception logging
=> PSR compatible exception logging

composer.json, src/views/site/_releaseRequestForm.php
- Removed legacy functionality in the "Create release request" form
=> Removed legacy feature
